# file: ntp/tasks/main.yml

- name: ntp | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - ntp
    - ntpdate

- name: ntp | Check for apparmor
  command: "dpkg -s apparmor"
  ignore_errors: True
  register: apparmor_check
  changed_when: False

- name: ntp | Update apparmor for leapseconds
  lineinfile:
    dest: "/etc/apparmor.d/usr.sbin.ntpd"
    line: "  /etc/ntp.leapseconds r,"
    regexp: ".+ntp.leapseconds.+"
    insertafter: ".+ntp.conf.+"
  when: apparmor_check.rc == 0
  notify:
    - reload ntp apparmor
    - restart ntp

- name: ntp | Fetch leapseconds file
  get_url:
    url: "{{ntp_leapurl}}"
    dest: "/etc/ntp.leapseconds"
    owner: "root"
    group: "root"
    mode: "0660"
  notify:
    - restart ntp

- name: ntp | Configure ntp (/etc/ntp.conf)
  template:
    src: etc_ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp

- name: ntp | Copy auto-ntpdate script
  copy:
    src: auto-ntpdate.sh
    dest: /usr/local/sbin/auto-ntpdate
    mode: 0770
  when: auto_ntpdate

- name: ntp | Generate auto-ntpdate cron
  cron:
    name: "ANXS auto-ntpdate"
    hour: "*/{{auto_ntpdate_hour}}"
    minute: "0"
    state: present
    job: "/usr/local/sbin/auto-ntpdate"
  when: auto_ntpdate

- name: ntp | Remove auto-ntpdate script
  cron:
    name: "ANXS auto-ntpdate"
    state: absent
  when: not auto_ntpdate

- name: ntp | Remove auto-ntpdate files
  file:
    path: /usr/local/sbin/auto-ntpdate
    state: absent
  when: not auto_ntpdate
