---
- name: restart ntp
  service:
    name: "{{ ntp_service_name }}"
    state: restarted
  when: ntp_running

- name: reload ntp apparmor
  command: apparmor_parser -r /etc/apparmor.d/usr.sbin.ntpd

- name: reload systemd
  systemd:
    daemon_reload: true

- name: enable auto-ntpdate timer
  systemd:
    name: auto-ntpdate.timer
    state: started
    enabled: true
